apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjoge30sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHt9LAoJCSJodWIuYXJ0b3guZGV2Ijoge30sCgkJInJlZ2lzdHJ5LmhldHpuZXIuYXJ0b3hsYWIuY29tIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJvc3hrZXljaGFpbiIsCgkiY3VycmVudENvbnRleHQiOiAib3Jic3RhY2siLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
